### ISSUE TITLE
Startup error on v0.106

### ISSUE THREAD

**Issue by viktorlevadnyi** [e2m32/hass_custom_timer#3]
Running Home Assistant 0.106.6 on Raspberry Pi 3b+ 

> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 432, in _async_add_entity
>     await entity.async_added_to_hass()
>   File "/config/custom_components/timer/__init__.py", line 326, in async_added_to_hass
>     self._remaining = self._end - dt_util.utcnow().replace(microsecond=0)
> TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'

**Comment by e2m32** [comment]
Thanks @viktorlevadnyi I'll look into it. Sorry for the delay, a lot going on these days.

**Comment by tjhiwa** [comment]
I've got the same error for HA 0.109.6 on VMware.

> Logger: homeassistant.setup
Source: custom_components/timer/__init__.py:326
First occurred: 3:29:45 PM (1 occurrences)
Last logged: 3:29:45 PM
> 
> Error during setup of component timer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 171, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/timer/__init__.py", line 139, in async_setup
    [{CONF_ID: id_, **cfg} for id_, cfg in config.get(DOMAIN, {}).items()]
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 134, in async_load
    await self.notify_change(event, item_id, item)
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 111, in notify_change
    await listener(change_type, item_id, item)
  File "/usr/src/homeassistant/homeassistant/helpers/collection.py", line 269, in _collection_changed
    await entity_component.async_add_entities([entity])
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 443, in _async_add_entity
    await entity.async_added_to_hass()
  File "/config/custom_components/timer/__init__.py", line 326, in async_added_to_hass
    self._remaining = self._end - dt_util.utcnow().replace(microsecond=0)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'

**Comment by darkkatarsis** [comment]
Same here on Home Assistant 2020.12.1, any chance to fix this?

**Comment by e2m32** [comment]
I'll put something together this week. I haven't been able to recreate this, but it should be a simple fix.

**Comment by e2m32** [comment]
@darkkatarsis @tjhiwa @viktorlevadnyi Please test latest commit. I've tested on `2020.12.2` and it seems to be working for me.
